name: Build and Deploy via SSH

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔨 Build project
        run: npm run build

      - name: 🚀 Deploy via SFTP
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ${{ secrets.DESTINATION }}
          source-path: dist/
          delete-target: true
